### ISSUE TITLE
Third party modules constructor function properties become read-only

### ISSUE THREAD

**Issue by edmcmanwich** [mozilla-jetpack/jpm#286]
If I place the following in index.js 'bar' is echoed out into the Browser Console without any issues
```
'use strict';

function Foo() {
	this.$data = false;
}

Foo.prototype.change = function(data) {
	this.$data = data;
};

var Test = new Foo();

Test.change('bar');

console.log(Test.$data);
```

But if I place the following in a file called test.js
```
'use strict';

function Foo() {
	this.$data = false;
}

Foo.prototype.change = function(data) {
	this.$data = data;
};

module.exports = new Foo;
```

and require it from index.js 
```
var Foo = require('js/test');
Foo.change('bar');
```

I get a TypeError complaining that $data is read-only. How can I require third-party modules that use constructor function properties?

**Comment by bmenant** [comment]
I’ve experienced the same issue. Looks like module exports are frozen (for security reasons?)
For your own modules, you could export a getter for your singletons, such as:

```javascript
// [...]
var _singleton = null
module.exports = function () {
  return _singleton || (_singleton = new Foo())
}
```

But for third party modules, you’ll probably have to fork them with a getter-wrapper...

Actually, this behavior is a bit confusing since neither NodeJS, nor Browserify implementation of CommonJS specs freezes module exports. Moreover, I think it’s pretty much the way people are used to define singleton with CommonJS (https://stackoverflow.com/questions/24283362/singleton-pattern-with-browserify-commonjs), aren’t they?

**Comment by jsantell** [comment]
This is intended behaviour for the SDK environment -- any discussion for this should be added to the [sdk bugs](https://bugzilla.mozilla.org/enter_bug.cgi?product=Add-on%20SDK&component=General), but it's unlikely to be changed at this point
