### ISSUE TITLE
Implement --update-link

### ISSUE THREAD

**Issue by erikvold** [mozilla-jetpack/jpm#288]
should do what `cfx --update-link` does, which ignores updateKey..

**Comment by benmccann** [comment]
+1 we host our extension off our own site instead off of the Mozilla update site. I'm not sure how to package it anymore with jpm since the `--update-link` and `--update-url` options are missing

**Comment by rentrop** [comment]
+1

**Comment by FayneAldan** [comment]
@rentrop Pointless emails are pointless.
![](http://i.imgur.com/JUCDMvJ.png)
Please don't comment unless you have something useful to say. Thank you.

**Comment by benmccann** [comment]
@FayneAldan i don't think it's pointless to express which issues are meaningful to you as it helps prioritize which features would be worked on. GitHub doesn't have any sort of issue voting or other means of expressing interest. Posting a huge image that provides little substance on the otherhand...

**Comment by FayneAldan** [comment]
@benmccann Subscribing to the issue can help. My point is that I don't want to be getting an email just saying "+1" because I subscribed to the issue. As for the screenshot, I will change that to a link.

**Comment by guyzmuch** [comment]
Actually, I implemented this and put a pull request (couple of month ago).
It was not merge, because they were before some test not passing, preventing an automatic merge.
https://github.com/mozilla/jpm/pull/301
I guess, I am not the only one that didn't get there merge request approve manually to the project (or having feedback about what to change)

**Comment by jsantell** [comment]
Handled in #301 , #354
