### ISSUE TITLE
Does not generate .update.rdf

### ISSUE THREAD

**Issue by benmccann** [mozilla-jetpack/jpm#313]
When I ran "cfx xpi" it output a My_Extension.update.rdf file. It seems that `jpm` doesn't support this yet?

Others have run into this issue as well. See https://gist.github.com/kentbrew/c0abb53a638279df306d

**Comment by rentrop** [comment]
+1

**Comment by jsantell** [comment]
I believe #325 fixes this -- please reopen otherwise!

**Comment by jaragunde** [comment]
The point of this issue is that jpm cannot generate an .update.rdf file like cfx used to do. This file is required by FF to check for updates in self-hosted add-ons, I think it is not needed any more for add-ons in AOM.

#325 is related with the generation of the install.rdf and I don't see how it fixes the generation of the .update.rdf file, actually I'm trying jpm from master and I cannot see how to do it.

**Comment by jsantell** [comment]
@jaragunde you're correct, I misunderstood this -- reopening

**Comment by guyzmuch** [comment]
This is a duplicate from https://github.com/mozilla-jetpack/jpm/issues/288. It can be closed.
(There is also a pull request for this waiting to be merge https://github.com/mozilla-jetpack/jpm/pull/301)

**Comment by benmccann** [comment]
@jsantell @Mossop @erikvold would one of you guys be able to review this? it's a blocker for us to migrate from cfx to jpm

**Comment by jsantell** [comment]
Checking this out today!

**Comment by anaran** [comment]
This new feature is now also appropriately documented at
https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#Supporting_updates_for_self-hosted_add-ons
as part of the fix for
https://bugzilla.mozilla.org/show_bug.cgi?id=1211430
