### ISSUE TITLE
Firefox mobile don't show button from package.json

### ISSUE THREAD

**Issue by Feverqwe** [mozilla-jetpack/jpm#326]
Hello! In Firefox mobile button don't display.
```
"preferences": [
    {
      "type": "control",
      "label": "Settings",
      "name": "settingsBtn",
      "title": "Settings"
    }
  ],
```

**Comment by ncalexan** [comment]
On Wed, Aug 19, 2015 at 7:08 PM, Anton <notifications@github.com> wrote:

> Button don't display.
> "preferences": [
> {
> "type": "control",
> "label": "Settings",
> "name": "settingsBtn",
> "title": "Settings"
> "title": ""
> }
> ],
>
Firefox for Android doesn't support XUL preferences, which is how such
things are arranged on Desktop.  @leibovic may know more.  Margaret?

**Comment by Feverqwe** [comment]
@ncalexan But in Add-on SDK it work, I try migrate and have this problem,

**Comment by ncalexan** [comment]
On Thu, Aug 20, 2015 at 8:17 AM, Anton <notifications@github.com> wrote:

> @ncalexan <https://github.com/ncalexan> But in Add-on SDK it work, I try
> migrate and have this problem,
>
Really?  I was not aware this worked in Firefox for Android, ever.  I can't
speak to what the jpm issue is, then :(

**Comment by palant** [comment]
Add-on SDK 1.14 and JPM are using different approaches in order to display inline options. Add-on SDK generates an actual `options.xul` file for the options whereas JPM uses a dummy for the options and relies on the SDK code in the browser to insert the real content (via sdk/preferences/native-options.js). So incompatibilities aren't really surprising.

This change isn't really related to JPM however - a newer version of CFX (from Add-on SDK repository) will produce the same result. Any issues with native options are rather Add-on SDK bugs and regressions from https://bugzilla.mozilla.org/show_bug.cgi?id=903039.

**Comment by kumar303** [comment]
> This change isn't really related to JPM however

I agree. You may have more luck filing an SDK bug https://bugzilla.mozilla.org/buglist.cgi?component=General&product=Add-on%20SDK&bug_status=__open__&list_id=12751883
