### ISSUE TITLE
Fix the tests

### ISSUE THREAD

**Issue by andymckay** [mozilla-jetpack/jpm#374]
We've got a pile of pull requests, but the tests are all failing for them. To keep the awesome pull requests coming, I think first we should fix the tests, then we can look at the pull requests and hopefully run them against the pull requests again.

**Comment by johannhof** [comment]
+1000

I thought #333 fixed tests though, maybe just give'em a restart on Travis?

**Comment by johannhof** [comment]
While at it, we should also update our Travis config to some less ancient version of Node.

**Comment by andymckay** [comment]
If that's the case I think the pull-requestee can re base their branch on #333 and re-kick the tests. Would be cool to merge these PRs, but so many failing tests on them.

**Comment by rpl** [comment]
@andymckay @johannhof unfortunately in #333 we fixed all the tests which fail consistently, but there are still a couple of intermittent test cases (they seem to fail for timeout reasons).

In #333 we decided to merge and then check how frequent they are, but now it is evident that they are pretty frequent so I'm going to try to get the time to give it another (deeper) look.

**Comment by rpl** [comment]
@andymckay @johannhof @kumar303 
During this weekend I fought with these intermittents tests, and I have two sad news and one good news:

- sad news: I'm unable to reproduce the problem locally, but it happens pretty often on travis,
  I tried different strategies and tried to run the same job on travis as much times as needed to make it fails  (and because of this travis probably hates me a lot now :-))

- good news: in #384 introduce a small change on one of the greatest test case offender: "jpm run addons - chrome", which presented the higher frequency of timeouts

- sad news: a jpm process which timeouts on a test case can (and it does) generate a random failure in another test case (because it runs "https://github.com/mozilla-jetpack/jpm/blob/90632d4/test/utils/index.js#L102" when another test case is running), I'm trying different strategies here but none that I like and which is effective

**Comment by johannhof** [comment]
First of all thanks for the effort :+1:

I can't put much time into it right now, but is there any way we can approach these tests from a different angle, e.g. completely rewrite they way they work instead of hacking around all these intermittents? That might even be faster now.

**Comment by erikvold** [comment]
+1

**Comment by rpl** [comment]
@johannhof unfortunately (imho) rewriting the test suite is not an option until we have a precise understanding on what generates the intermittent timeout failures (or we can end up with the same issue on the rewrote test suite).

Some of the test cases that turn into timeout failures during my experimentations were actually completely successfully but the Firefox instance which runs the test addon did not exit after complete the code they had to run without an evident reason.

it would be way better if I could recreate the issue locally: I'm going to try to run the test suite locally on a Xfvb like on Travis to check if it is connected somehow to the behaviour presented on Travis.

**Comment by kumar303** [comment]
I think the tests are stable enough right now. I've been reviewing a lot of pull requests lately and I can't remember the last time I saw a flaky failure as opposed to a real failure.
