### ISSUE TITLE
jpm xpi generates invalid .update.rdf

### ISSUE THREAD

**Issue by benmccann** [mozilla-jetpack/jpm#440]
This line is broken:
https://github.com/mozilla-jetpack/jpm/blob/master/lib/rdf.js#L158

The tool is exporting:

    <Description about="urn:mozilla:myext@myext.com">

When it should be exporting:

    <Description about="urn:mozilla:extension:myext@myext.com">

No users of our extension got the update to the latest version of our extension because of this bug :-(  Which meant they all have unsigned versions installed, which turned out to make this an awesome day with FF43 rolling out.

https://developer.mozilla.org/en-US/docs/Extension_Versioning,_Update_and_Compatibility

>It is important to get the initial RDF:Description's about attribute correct. It varies depending on what type of add-on you are providing information for:
>
>* For an extension or plugin bundle it must be urn:mozilla:extension:<id>
* For a theme it must be urn:mozilla:theme:<id>
* For any other type of add-on it must be urn:mozilla:item:<id>

**Comment by benmccann** [comment]
@guyzmuch @kumar303 either of you guys know if we can just hardcode an extra "extension:" to fix this? jpm isn't used to build themes or other types of add-ons is it?

**Comment by kumar303** [comment]
Huh. The about formatting (without `:extension`) has been the same since it was added [back in May](https://github.com/mozilla-jetpack/jpm/commit/9b31b885). Did something change in Firefox?

Either way, if there's a fix, I'd be happy to get it in. I don't think jpm is used for themes but I also don't know much about how updates work.

@rpl do you have some familiarity here to help make a decision on how to fix the `about` property?

**Comment by benmccann** [comment]
He wrote the code back in May, but no one got around to merging it until October https://github.com/mozilla-jetpack/jpm/commit/004f02915b748345a95e2068b64c02178bda0b14. This is the first release we've cut with `jpm` instead of `cfx`. I'm pretty sure it was just broken when initially written and merged

**Comment by kumar303** [comment]
oh, I see.

**Comment by benmccann** [comment]
Sent a PR for this: https://github.com/mozilla-jetpack/jpm/pull/441

**Comment by kumar303** [comment]
Thanks again

**Comment by benmccann** [comment]
Thanks for being so responsive!  If you know anyone on the addon-sdk I have some bug fixes from August I'm still trying to get merged :-)

**Comment by kumar303** [comment]
oh, sorry, we had some mis-communication about the Add-on SDK because the code moved to a different repository. You can see all bugs here https://bugzilla.mozilla.org/buglist.cgi?component=General&product=Add-on%20SDK&bug_status=__open__&list_id=12751883 I'd suggest filing a new bug about it in bugzilla. Someone can help you patch against the new repo (which is mozilla-central).
