### ISSUE TITLE
jpm sign: Version does not match install.rdf. ( status: 400 )

### ISSUE THREAD

**Issue by pnguyen-pi** [mozilla-jetpack/jpm#450]
Hi everybody,

I tried to use "jpm sign" command to retrieve a new XPI for my add-on signed by Mozilla. But I got a strange issue regard to version number does not match install.rdf file

> JPM [info] Signing XPI: 
> JPM [error] Server response: Version does not match install.rdf. ( status: 400 )
> JPM [info] FAIL

I verified the install.rdf file and its version is 2.14.7. Also tried to installed this XPI to my FF browser and it still displayed version of 2.14.7 in the FF browser. Not sure how I got this issue and how to bypass it because I also tried to create a new submission of this XPI manually on Develop Hubs and no issue/warning is returned like above.

Please help me on this issue.

**Comment by kumar303** [comment]
Hi. I think jpm may be detecting the version wrong. Is it possible to upload the XPI file you were trying to sign? Were you running it like `jpm sign --xpi=path/to/the.xpi` ?

**Comment by kumar303** [comment]
Aha. I found a file with an alternate RDF that reproduces this bug.

(grrr, github won't let me attach an XPI).

**Comment by kumar303** [comment]
The code is looking for a manifest in the XPI, not finding it, and posting to `/api/v3/addons/null/versions/undefined/`, d'oh. Yay javascript.

**Comment by pnguyen-pi** [comment]
@kumar303  I used the command as below to get signning from Mozilla

>jpm sign --api-key "user:11853170:122" --api-secret "secret" --xpi "path/to/the.xpi"

I am looking forward your fix (^.^)

Thank you so much.

**Comment by zeird** [comment]
> The code is looking for a manifest in the XPI, not finding it, and posting to /api/v3/addons/null/versions/undefined/, d'oh. Yay javascript.

So would the next versions of `jpm sign` ignore the absence of version number in package.json?

**Comment by notnarb** [comment]
As suggested in https://github.com/mozilla-jetpack/jpm/pull/456 this (at least for me) is caused by a lack of a package.json within the xpi (mine was created with crx).  

A quick and dirty fix that worked for me was to just ```zip <filename>.xpi package.json``` as part of my build process since I can't seem to find a way to inform crx that I wish to have the package.json included.

**Comment by kumar303** [comment]
I think this has been fixed as part of #465. Could you test it out following these [install instructions](https://github.com/mozilla-jetpack/jpm/#install) to see if it works before we publish a release?

**Comment by kmoir** [comment]
I was able to run the jpm sign command last night on the test addons for the xpcshell test suites addons. Thanks! However, the unlisted addons are in a state of "Preliminarily Reviewed" and don't appear to have artifacts associated with the signing in them, despite receiving the email that they are signed. Unsure if this is because they are in the "Preliminarily Reviewed" state.

**Comment by kumar303** [comment]
That is definitely unexpected. I filed this to track it: https://github.com/mozilla-jetpack/jpm/issues/470

**Comment by kumar303** [comment]
Due to this and other comments I think the `install.rdf` support is working. File new bugs if anyone runs into any.
