### ISSUE TITLE
JPM not detecting Firefox developer

### ISSUE THREAD

**Issue by GlitcherWolf** [mozilla-jetpack/jpm#453]
>JPM [info] Creating a new profile
>JPM [error] No Firefox binary found at null
>JPM [error] Specify a Firefox binary to use with the `-b` flag.
>JPM [error] Error: spawn C:\Program Files (x86)\Mozilla Firefox\firefox.exe ENOENT

The Firefox developer directory path is C:\Program Files (x86)\Firefox Developer Edition\firefox.exe.
Any way to direct JPM to the right path?

**Comment by kumar303** [comment]
What is the full command you were running? You need to use `-b` to specify the binary path.

**Comment by lv7777** [comment]
this problem is troubled by many people.
https://github.com/mozilla-jetpack/jpm/issues/297
https://github.com/mozilla-jetpack/jpm/issues/287

I also have same problem,but resolved by install firefox(not dev edition)

**Comment by GlitcherWolf** [comment]
Yeah just used the -b flag and it works completely. Just needed to define the entire path from the root.

**Comment by oxidian24** [comment]
Hi, I have same problem but I have Firefox installed on non system partition on Windows. Is it possible to tell jpm where my binaries are placed? First I tried to run jpm -b with a path like P:\.... then "P:\...." because the path contains spaces. But nothing works. Then I tried to switch to p: and run it as /my/path/to/firefox and it also did not work. Everytime I get message No Firefox binary found at null. But what does it really mean?

**Comment by freaktechnik** [comment]
It means JPM can't figure out where the Firefox binary is installed using the registry. Either, because it's unrecognized branding or because the registry record is not set properly.

**Comment by oxidian24** [comment]
Registry is SOFTWARE/Mozilla/Mozilla Firefox 47.0.1/bin/PathToExe: value: P:\INTERNET\BROWSERS\FF 47\firefox.exe
How can I fix the problem?

**Comment by kumar303** [comment]
As a workaround, you can use the `--binary` option to specify the exact path to Firefox: https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#jpm_run

**Comment by oxidian24** [comment]
That is what I am doing. But it does not detect the binaries. I have not idea how to do it. I just fails. I gave here the path, can you gave me the exact command which will work. As nothing worked till now. How JPM will detect on which partition is the firefox located? I cannot write something like jpm -b "P:/my/path/to/firefox" because it will not detect the binary. So I ask why.

**Comment by oxidian24** [comment]
Update: as written here: https://github.com/mozilla-jetpack/jpm/issues/451
akisman commented on 23 Dec 2015
"Although it doesn't automatically detect ... , you can use the -b ...  or set up the JPM_FIREFOX_BINARY environmental variable(you may need a restart after) as mentioned in the Docs."

I did and now it writes:
U:\addons\test>jpm run
JPM [info] Starting jpm run on My Jetpack Addon
JPM [info] Creating a new profile
JPM [error] No Firefox binary found at null
JPM [error] Specify a Firefox binary to use with the `-b` flag.
JPM [error] Error: spawn P:\INTERNET\BROWSERS\FF 47 ENOENT

But the path is correct.

**Comment by kumar303** [comment]
Huh. There could be a bug in our code triggered by the space in the filename. Could you rename the application directory to `FF-47` and try it as `P:\INTERNET\BROWSERS\FF-47` ?

**Comment by kumar303** [comment]
thanks for creating a new issue :) I moved discussion to https://github.com/mozilla-jetpack/jpm/issues/545
