### ISSUE TITLE
Support localization of add-on's name and description

### ISSUE THREAD

**Issue by johannhof** [mozilla-jetpack/jpm#479]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1218719

Currently you have to manually edit the generated install.rdf file to localize an addon's name or description. It would be cool if JPM could do that automatically.

The easiest way to do it is described in [1218719](https://bugzilla.mozilla.org/show_bug.cgi?id=1218719), where you could just define `NameOfTheAddon_description=localized description of my addon` in `locale/ja.properties`. @kumar303 Does that sound like a good solution?

This is semi-blocking a current work thing of mine, so I'd love to be able to fix it myself soon.

**Comment by jc3213** [comment]
It's a bug reported just by me on bugzilla, I'm now using this way to localize the description(since title is not supported). Here's the sample. or you can get my source from https://github.com/mozilla-jetpack/jpm/files/108789/Simple_Proxy.zip

`var SimplePrefs = require("sdk/simple-prefs");
var Locales = require("sdk/l10n").get;
SimplePrefs.prefs["description"] = Locales("add-on description");`

**Comment by johannhof** [comment]
Yeah it's a good hack but I think having a magic key in the properties file sounds like a good permanent solution (which also works for the add-on title). It should also be easy to implement it in JPM.

**Comment by jc3213** [comment]
@johannhof Anyway,is there any chance that I can use &abc; in package.json to set abc as a l10n key in the locale.properties, as I used to do in options.xul before?

It will be very helpful if there are options that uses the same l10n value.Currently pref-name_options."value in the option label"=translation string is too long. and if more than one option in deferent pref-name has the same string.it will cause lots of bytes to fulfill the l10n as I only use 2 line when it is options.xul

PS:I don't speak English as my native, since I am a Chinese.Maybe https://bugzilla.mozilla.org/show_bug.cgi?id=1210758 has better explanation than I reported here

**Comment by johannhof** [comment]
@jc3213 No worries, I understand what you're looking for. I think it's a reasonable idea, but I'd recommend making a new issue since it's not directly related to the name and description thing :)

**Comment by asamuzaK** [comment]
FYI:
1123428 – Let developers localize add-on metadata with jpm
https://bugzilla.mozilla.org/show_bug.cgi?id=1123428

Provide a way to localize package.json information · Issue #562 · npm/newww
https://github.com/npm/newww/issues/562

**Comment by johannhof** [comment]
Wow I didn't notice there was an ongoing pull request for this already: #419. Too many pages argh :finnadie:

**Comment by kumar303** [comment]
Oh whoops, that one still needs some fixups. Maybe it will help serve as a reference though.

**Comment by johannhof** [comment]
Should be closed by #495 :tada:
