### ISSUE TITLE
Can't use node core module name for custom third-party module

### ISSUE THREAD

**Issue by toberndo** [mozilla-jetpack/jpm#497]
If a dependency has a name of a node core module, e.g. `require('punycode')` then jpm won't find a third-party module with the same name in the /node_modules folder of the add-on.

Running the example attached will lead to: "Message: Module `punycode` is not found at resource://gre/modules/commonjs/punycode.js"

[jpm core modules.zip](https://github.com/mozilla-jetpack/jpm/files/136799/jpm.core.modules.zip)

**Comment by freaktechnik** [comment]
This is an SDK issue and not a jpm issue, jpm doesn't worry about dependencies/modules. It also seems this is by design: https://dxr.mozilla.org/mozilla-central/source/addon-sdk/source/lib/toolkit/loader.js#713. I would assume this is to keep them reserved for https://bugzilla.mozilla.org/show_bug.cgi?id=935108, if that ever happens...

**Comment by toberndo** [comment]
Ok, understandable. As a work around I renamed the dependency. Thanks!
