### ISSUE TITLE
--silent option

### ISSUE THREAD

**Issue by meandavejustice** [mozilla-jetpack/jpm#504]
Our team is in the process of automated the build/signing  of our addon with a build server. Unfortunately `jpm sign` throws if run with a version that has already been signed, breaking our process. I wrote a little script to work around this for the time being. We would eventually like to be able to use `jpm sign` directly. Maybe a `--silent` option would work. I talked with @kumar303 briefly last week on irc and it sounds like there may need to be a bit of refactoring to achieve this.

Here is our workaround (maybe helpful for others)
```javascript
#!/usr/bin/env node
const version = require('../package.json').version;
const resolve = require('path').resolve;
const xpiPath = resolve(`dist/testpilot-addon-${version}.xpi`);

const cmdStr = `jpm sign --api-key ${process.env['AMO_USER']}
               --api-secret ${process.env['AMO_SECRET']}
               --xpi ${xpiPath}`;

require('child_process').exec(cmdStr, (err, stdout) => {
  if (err) return console.error(err);
  console.log(stdout);
});

```

**Comment by kumar303** [comment]
I'm going to close this because what you're asking (correct me if I'm wrong) is to make the output of jpm better so that you can scrape the test from a script.

Instead, I'd rather add features to jpm that lets you use it more effectively from a script. You can use `sign` directly like:

````javascript
var sign = require('jpm/lib/sign').sign;
var options = {
  addonDir: '...',
  apiKey: '...',
  apiSecret: '...',
};
sign(options)
  .then(function(result) {
    console.log(result.success ? "SUCCESS" : "FAIL");
  })
  .catch(function(error) {
    console.error('got error', error);
  });
````

You should be able to do regular expression matching on the error to catch and handle duplicate versions.

If that's too tricky, the best thing would be to open a new issue asking for a new property on `result` (or something) that would allow you to programmatically handle duplicate versions.

**Comment by meandavejustice** [comment]
@kumar303 being able to access jpm from a script like your above snippet would solve my issue.

I was not asking for better output though. I want to be able to silence the error thrown from `jpm sign` so that I can chain commands together in our build. for example:

```
jpm package && jpm sign --xpi path/to/addon.xpi && mv addon.xpi ../static/addon.xpi
```

currently, jpm will throw if the version has already been signed, exiting and breaking our process.

**Comment by kumar303** [comment]
> I was not asking for better output though. I want to be able to silence the error thrown from jpm sign so that I can chain commands together in our build.

Okay but I still don't want to introduce this change because it would break other uses of the `jpm sign` command. For example, some developers automate `jpm sign` to publish a build after they land a pull request. If they tried to publish a duplicate version then that would be an error so their script should fail.

Another option is you can use your own wrapper script. Call it `jpm-sign-with-dupes-allowed.js` (or whatever) and use the snippet I pasted above. Then run it in your chain like:

````
jpm package && jpm-sign-with-dupes-allowed.js --xpi path/to/addon.xpi && mv addon.xpi ../static/addon.xpi
````

However, I am still unclear why you want to ignore the error about publishing a duplicate version. This sounds like a bug in your build process that you should fix. You can increment the version number in your `package.json` file to avoid publishing a duplicate version.
