### ISSUE TITLE
matchpattern or pageMod include does not match paths in url

### ISSUE THREAD

**Issue by Gamesh** [mozilla-jetpack/jpm#526]
I've read the https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/util_match-pattern many times and it's still unclear why the `pattern: *.eztv.it/myshows/` does not match `url: https://eztv.it/myshows/`

does the string wildcard only work for domains and it's not documented ? or it's a bug?
it seams that the path part is completely ignored. 
I'm using jpm 1.0.7

**Comment by freaktechnik** [comment]
First off, the correct place to ask such questions would be on [discourse](https://discourse.mozilla-community.org/c/add-ons/development), IRC, StackOverflow or any other place linked on https://developer.mozilla.org/en-US/Add-ons/SDK. This is a bug tracker for issues within JPM, which only packages up files and doesn't contain the SDK. That's also why the jpm version is irrelevant.

Now to your issue: this doesn't work, because wildcarded URLs can't have a path, it just matches against the domain, which it thinks is `eztv.it/myshows/`  which will never match any domain. Use a regular expression instead.

**Comment by Gamesh** [comment]
sorry for that, and thank you for your answer
