### ISSUE TITLE
jpm sign to support proxy server

### ISSUE THREAD

**Issue by vidyavijayabhanu** [mozilla-jetpack/jpm#601]
Is jpm sign command currently supporting running it through a proxy server(specifying proxy ip as argument)?
If so since which version?
Please reply with link to jpm binaries that support proxy server if code changes have been made

**Comment by freaktechnik** [comment]
See #446

**Comment by vidyavijayabhanu** [comment]
I want a working binary of jpm sign which supports proxy server.
I checked the thread but couldnt find

**Comment by freaktechnik** [comment]
sign-addon supports proxies. That thread is about integrating the proxy settings of sign-addon into jpm, however you can use sign-addon as standalone afaik.

**Comment by kumar303** [comment]
> Is jpm sign command currently supporting running it through a proxy server(specifying proxy ip as argument)?

No, not yet. The feature will be added in: https://github.com/mozilla-jetpack/jpm/issues/446 . No one is available to work on this currently but if you submit a patch I can help review it.

I'm closing this issue since it's a duplicate request.

Thanks for taking the time to file a bug. In the meantime, you can either write a script that uses [sign-addon](https://github.com/mozilla/sign-addon/) directly or you could install [web-ext](https://github.com/mozilla/web-ext) and do it in two steps:

````
jpm xpi
web-ext sign --proxy ... --xpi=/path/to/jpm-signed.xpi
````

**Comment by vidyavijayabhanu** [comment]
Please let me know if any release of jpm sign command supports proxy.
We have a pressing need where jpm sign command has to support proxy.
