### ISSUE TITLE
Error While runinng Addon in JPM in the Firefox Dev Browser

### ISSUE THREAD

**Issue by abinabrahamanchery** [mozilla-jetpack/jpm#605]
I was trying to create an Addon using the JPM but unable to run the addon in firefox stable because unsigned addons were blocked by the firefox browser ,so i downloaded the Firefox Dev Edition but unable to run the addon in firefox and getting error 

C:\Users\Abin\AppData\Roaming\npm\unisis>jpm run
JPM [info] Starting jpm run on Unisis
JPM [info] Creating a new profile
JPM [error] No Firefox binary found at null
JPM [error] Specify a Firefox binary to use with the `-b` flag.
JPM [error] Error: spawn C:\Program Files (x86)\Mozilla Firefox\firefox.exe ENOENT

Did any one knows how to fix this ???  I haven't find any solution online

**Comment by freaktechnik** [comment]
You have to specify the full path to firefox.exe for the Dev Edition with the `-b` flag as the error suggests. It only tries to find firefox via registry and then looks in a very common default location, from what I recall.

**Comment by kumar303** [comment]
The error message isn't so helpful (sorry about that) but this is not a jpm bug. @freaktechnik has provided the solution but you can consult the docs for more info: https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#jpm_run

Since it's not a jpm bug I'm closing the issue but feel free to reply to this thread if you still need help.
